font_family JetBrainsMonoNL Nerd Font
font_size 13
modify_font cell_height 160%

background_opacity 0.90

cursor_shape beam
cursor_blink_interval 0

enable_audio_bell no

window_padding_width 0

# BEGIN_KITTY_THEME
# Solarized Dark
include current-theme.conf
# END_KITTY_THEME
